apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: robipresotto/frontend:latest
        name: frontend
        ports:
        - containerPort: 80