apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: app
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: robipresotto/api-gateway:latest
        name: api-gateway
        ports:
        - containerPort: 8080