apiVersion: v1
kind: Service
metadata:
  name: minio-client
  namespace:  app
  annotations:
    linkerd.io/inject: enabled
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: minio-client