minimumMasterNodes: 1
replicas: 2

antiAffinity: "soft"
esJavaOpts: "-Xmx128m -Xms128m"

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M    

service:
  annotations: 
    linkerd.io/inject: "enabled"

secret:
  enabled: true
  password: ${password}