podSecurityPolicy:
  enabled: true

server:
  persistentVolume: 
    enabled: ${persistentVolume}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi