testkube-api:
  slackToken: 
  slackTemplate: 
  slackConfig: 

  minio:
    enabled: false

  storage:
    endpoint: "minio.storage:9000"
    accessKeyId: ${minioAccessKeyId}
    accessKey: ${minioAccessKey}

  service:
    annotations: 
      linkerd.io/inject: "enabled"

  prometheus:
    enabled: false

telemetryEnabled: ${telemetry}
